### PR TITLE
Issue 6 - handle project CRUD routes/controllers for unauthorized users

### PR DESCRIPTION
**Pull request by AnnaSolovykh**
1. Add .env.example as an example how env is going tom look like for now
2. Add async wrapper for cleaner code in the controller 
3. Install http-status-codes for easier status handling => please use npm install before running the code
4. Fix Technologies model
5. Populate DB with mock data for testing - mock data does not have applicants, participants and createdBy as we have not users yet
6. Implement get request for unauthorised users:
- Check pagination in Postman (for example, http://localhost:8000/api/v1/projects?page=2&limit=2)
- Check search feature in Postman(for example, http://localhost:3000/api/v1/projects?search=backend)
- Or combined, for ex., http://localhost:3000/api/v1/projects?search=react&page=2&limit=1

### CODE REVIEW

**Review by JDOdea — APPROVED** [review]
looks great!

**Review by DYA13 — APPROVED** [review]
👍

**Comment by secch97** [comment]
**GET Requests on my end:**

- **Projects pagination**:
  image

- **Projects w/Search feature**
  
  image

- **Projects w/Search & Pagination feature**
image


Might be worth to say that I had to change this api request:  `http://localhost:8000/api/v1/?page=2&limit=2` to `http://localhost:8000/api/v1/projects?page=2&limit=2` to make it work on my end


Nice job!!!!

**Comment by AnnaSolovykh** [comment]
Thanks a lot for reviewing! 
I appreciate it! 

Right, it was a type... I was doubting a lot whether the path should be / or /projects. Now we have projects but we won't have any request for / in the app. I am not sure if it is fine. It finally seemed to me that as we search though the projects, url with projects might be more consistent🤔

**Comment by secch97** [comment]
> Thanks a lot for reviewing! I appreciate it!
> 
> Right, it was a type... I was doubting a lot whether the path should be / or /projects. Now we have projects but we won't have any request for / in the app. I am not sure if it is fine. It finally seemed to me that as we search though the projects, url with projects might be more consistent🤔

I agree too on URL with projects being more consistent!

**Pull request merged**
