### PR TITLE
Issue 8 - Feature/set up basic models

### PR DESCRIPTION
**Pull request by AnnaSolovykh**
[Issue](https://github.com/Code-the-Dream-School/ffprac-team1-back/issues/8 )

Models for Project and Technologies, ProjectLikes are added; 
User model is updates with new fields and validation.

### CODE REVIEW

**Review by JDOdea — APPROVED** [review]
looks good to me!

**Comment by AnnaSolovykh** [comment]
> looks good to me!

Thanks for reviewing!

**Review by secch97 — APPROVED** [review]
Well done! Everything looks fine to me. 

I am just wondering if you are going to keep updating the user model or is that your finished model? I am just basing myself on the Entities-Relation DB Model.

giphy

**Comment by AnnaSolovykh** [comment]
> Well done! Everything looks fine to me. 
> 
> 
> 
> I am just wondering if you are going to keep updating the user model or is that your finished model? I am just basing myself on the Entities-Relation DB Model.
> 
> 
> 
> giphy
> 
> 

Thank you a bunch!
No, it is not finished. 

Actually Yelena is going to continue with hashing password etc in the model, registration and login, we have just decided upon me adding the entities we have added during the previous meeting. But for sure this is not the last version...🤪

**Review by DYA13 — APPROVED** [review]
Looks good to me👍

**Pull request merged**
