### PR TITLE
Main register functionality added, connection to Mongo DB established

### PR DESCRIPTION
**Pull request by DYA13**
image
image
image

### CODE REVIEW

**Review by AnnaSolovykh — APPROVED** [review]
Works fine!
Screenshot 2024-03-07 at 13 55 49
Screenshot 2024-03-07 at 13 55 59

**Comment by AnnaSolovykh** [comment]
The only is thing is that PORT 3000 - is our frontend port. Our backend PORT should be 8000 by default. 


`Server is running on port 3000 `- from app.js
`Listening on Port 8000! ` - from server.js


In server.js PORT 8000 is precoded as env(`const { PORT = 8000 } = process.env`), in app.js -` const PORT = process.env.PORT || 3000`. I guess, we do not need server.js any more and favicon icon, and we need to change port to 8000 in app.js. What are your thoughts about that?

**Review by JDOdea — APPROVED** [review]
Looks good!

**Comment by DYA13** [comment]
> The only is thing is that PORT 3000 - is our frontend port. Our backend PORT should be 8000 by default.
> 
> `Server is running on port 3000 `- from app.js `Listening on Port 8000! ` - from server.js
> 
> In server.js PORT 8000 is precoded as env(`const { PORT = 8000 } = process.env`), in app.js -` const PORT = process.env.PORT || 3000`. I guess, we do not need server.js any more and favicon icon, and we need to change port to 8000 in app.js. What are your thoughts about that?

In my understanding, server.js is created for optimization if our project will grow huge in the future. We can delete server.js as well  and edit code in app.js, for me no problem. We can also do it later as well. May be @JDOdea  and Saul could advise us how it will be better?

**Comment by AnnaSolovykh** [comment]
> > The only is thing is that PORT 3000 - is our frontend port. Our backend PORT should be 8000 by default.
> > `Server is running on port 3000 `- from app.js `Listening on Port 8000! ` - from server.js
> > In server.js PORT 8000 is precoded as env(`const { PORT = 8000 } = process.env`), in app.js -` const PORT = process.env.PORT || 3000`. I guess, we do not need server.js any more and favicon icon, and we need to change port to 8000 in app.js. What are your thoughts about that?
> 
> In my understanding, server.js is created for optimization if our project will grow huge in the future. We can delete server.js as well and edit code in app.js, for me no problem. We can also do it later as well. May be @JDOdea and Saul could advise us how it will be better?

I am ok if server remains, your point makes sense!

**Comment by secch97** [comment]
Personally, I agree on having in our project a server.js file so app.js can deal with middleware & routing while server.js deals with requests. For me, this is a good practice.

Now, regarding the port number issue, I'd only use port 8000 for backend, leaving on server.js the app.listen as it would be already be requiring the app.js file.

Regarding the API on registering an user:
image
image

Working fine! 

giphy

**Pull request merged**
